import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { cookies } from "next/headers";
import { AuthProvider } from "./context/AuthContext";
import Navbar from "./_component/Navbar";

// Fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Layout
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // ✅ Server-side cookie check
  const cookieStore = await cookies();
  const isLoggedIn = cookieStore.has("token");

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}`}
    >
      <body className="min-h-screen flex flex-col">
        {/* ✅ Pass initial state to client */}
        <AuthProvider initialUser={isLoggedIn}>
          
          {/* Navbar must be client if using context */}
          <Navbar />

          {/* Pages */}
          <main className="flex-1">
            {children}
          </main>

        </AuthProvider>
      </body>
    </html>
  );
}